name: GCP Authentication

description: Authenticate to GCP and configure Docker

inputs:
  credentials_json:
    description: GCP service account credentials
    required: true

  registry:
    description: GCP Artifact Registry hostname
    required: true

runs:
  using: composite

  steps:
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.credentials_json }}

    - name: Configure Docker
      shell: bash
      run: |
        gcloud auth configure-docker \
          "${{ inputs.registry }}" \
          --quiet