name: deplo-and-update

on:
  workflow_call:
    secrets:
      GCP_CREDENTIALS:
        required: true
    inputs:
      TAG:
        required: true
        type: string
      MADOR:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string

env:
  REGION: me-west1
  REPOSITORY: ad-hatzot

jobs:
  
    
  update-image-tag:
    env:
      ENVIRONMENT: ${{ startsWith(github.ref, 'refs/tags/') && 'prod' || 'pre' }}
    runs-on: self-hosted
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Install yq
        uses: mikefarah/yq@v4
        
      - name: Get service name
        id: service
        run: |
          SERVICE_NAME=$(find . -mindepth 1 -maxdepth 1 -type d \
            ! -name .git \
            -printf '%f\n' | head -n 1)
  
          echo "Service name: $SERVICE_NAME"
          echo "service_name=$SERVICE_NAME" >> "$GITHUB_OUTPUT"
        
      - name: Update image tag
        run: |
          VALUES_FILE="${ENVIRONMENT}/values.yaml"
  
          yq -i '
            .["${MADOR}-helm"].objects[] |
            select(.name == env(SERVICE_NAME)) |
            .tag = env(IMAGE_TAG)
          ' "values.yaml"
  
      - name: Show changes
        run: git diff -- "$VALUES_FILE"
  
      - name: Commit and push
        run: |
          git config user.name "tamarhami"
          git config user.email "tamarhami@gmail.com"
  
          git add "$VALUES_FILE"
          git commit -m "Update ${SERVICE_NAME} image tag to ${IMAGE_TAG}" || echo "No changes"
          git push
