# .github/workflows/main.yml

name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_call:

jobs:
  build:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    uses: Devops-Had-Hatzot/ci-template/.github/workflows/build.yml@main

  mirror:
    runs-on: self-hosted
    if: startsWith(github.ref, 'refs/tags/')
    uses: Devops-Had-Hatzot/ci-template/.github/workflows/build.yml@main